const initSqlJs = require('sql.js');
const fs = require('fs');
const path = require('path');
(async () => {
  const SQL = await initSqlJs();
  const dbPath = path.join(__dirname, 'data', 'consignado.sqlite');
  const buf = fs.readFileSync(dbPath);
  const backup = path.join(__dirname, `data/consignado.sqlite.pre_drop_recurso_tre_${Date.now()}.sqlite`);
  fs.writeFileSync(backup, buf);
  console.log('Backup prévio SQLite criado:', backup, (buf.length/1024/1024).toFixed(2)+' MB');
  const db = new SQL.Database(buf);
  const before = db.exec(`SELECT COUNT(*) as c FROM sqlite_master WHERE type='table' AND name='Recurso TRE'`);
  console.log('Tabela existe antes (1=sim):', before[0]?.values[0][0]);
  db.run(`DROP TABLE IF EXISTS "Recurso TRE";`);
  const shaTRE = '965b2a12abd159c2b7053bdee8103d9888b0420f3534a602b4215ec4ae513993';
  let r;
  r = db.run(`DELETE FROM consignado_app_config WHERE key = 'imported_file_sha256::v1::${shaTRE}'`);
  console.log('DELETE L2 SHA TRE:', r.getRowsModified(), 'keys');
  r = db.run(`DELETE FROM imported_row_hashes WHERE kind = 'learning_profile:Recurso TRE'`);
  console.log('DELETE L1 row_hashes TRE:', r.getRowsModified());
  r = db.run(`DELETE FROM import_batch_rows WHERE kind = 'recurso_tre' OR target_table = 'Recurso TRE'`);
  console.log('DELETE import_batch_rows TRE:', r.getRowsModified());
  r = db.run(`DELETE FROM import_batches WHERE kind = 'recurso_tre' OR target_table = 'Recurso TRE'`);
  console.log('DELETE import_batches TRE:', r.getRowsModified());
  const after = db.exec(`SELECT COUNT(*) as c FROM sqlite_master WHERE type='table' AND name='Recurso TRE'`);
  console.log('Tabela existe depois (0=não):', after[0]?.values[0][0]);
  const outData = db.export();
  fs.writeFileSync(dbPath, Buffer.from(outData));
  console.log('SQLite persistido OK. Saia e reexecute oneshot TRE agora.');
  process.exit(0);
})().catch(e => { console.error('FATAL:', e); process.exit(1); });
