import * as _mod from './import-consignado.js';
type RecursoTarget = 'both' | 'extratos' | 'relatorio' | 'recurso_alego' | 'recurso_neoconsig_demais' | 'recurso_adfego' | 'recurso_tce' | 'recurso_tcm' | 'recurso_tre' | 'recurso_trt' | 'recurso_eletra' | 'recurso_mpgo' | 'recurso_tjgo';
export declare class ConsignadoService {
    readonly conciliarRecursoOrgaoRelatorio: typeof _mod.conciliarRecursoOrgaoRelatorio;
    readonly conciliarExtratoRelatorio: typeof _mod.conciliarExtratoRelatorio;
    readonly conciliarExtratoRelatorioDetalhe: typeof _mod.conciliarExtratoRelatorioDetalhe;
    readonly conciliarTemporario: typeof _mod.conciliarTemporario;
    readonly clonarParaRelatorioSisbrFromExtratos: typeof _mod.clonarParaRelatorioSisbrFromExtratos;
    readonly incluirServidorAcordoJudicialTjgo: typeof _mod.incluirServidorAcordoJudicialTjgo;
    readonly liquidacaoCcsExcluirRelatorioSisbr: typeof _mod.liquidacaoCcsExcluirRelatorioSisbr;
    readonly liquidacaoProcessoJudicialExcluirRelatorioSisbr: typeof _mod.liquidacaoProcessoJudicialExcluirRelatorioSisbr;
    readonly naoPossuiRecursoRelatorioSisbr: typeof _mod.naoPossuiRecursoRelatorioSisbr;
    readonly liquidacaoForaDoVencimentoRelatorioSisbr: typeof _mod.liquidacaoForaDoVencimentoRelatorioSisbr;
    readonly liquidacaoRecursoJudicialRelatorioSisbr: typeof _mod.liquidacaoRecursoJudicialRelatorioSisbr;
    readonly liquidacaoAntecipadaViaCaixaRelatorioSisbr: typeof _mod.liquidacaoAntecipadaViaCaixaRelatorioSisbr;
    readonly recursoRecebidoAMaiorRelatorioSisbr: typeof _mod.recursoRecebidoAMaiorRelatorioSisbr;
    readonly devolucaoParcialAverbacaoRelatorioSisbr: typeof _mod.devolucaoParcialAverbacaoRelatorioSisbr;
    readonly recursoRecebidoAMenorRelatorioSisbr: typeof _mod.recursoRecebidoAMenorRelatorioSisbr;
    readonly recursoJudicialValorAMenorRelatorioSisbr: typeof _mod.recursoJudicialValorAMenorRelatorioSisbr;
    readonly estornoValoresRelatorioSisbr: typeof _mod.estornoValoresRelatorioSisbr;
    readonly alterarOrgaoRelatorioSisbr: typeof _mod.alterarOrgaoRelatorioSisbr;
    readonly repactuacaoRelatorioSisbr: typeof _mod.repactuacaoRelatorioSisbr;
    readonly antecipadoDevolvidoRelatorioSisbr: typeof _mod.antecipadoDevolvidoRelatorioSisbr;
    readonly desfazerOcorrenciaRelatorioSisbr: typeof _mod.desfazerOcorrenciaRelatorioSisbr;
    readonly getOcorrenciaCloneParaSisbrContext: typeof _mod.getOcorrenciaCloneParaSisbrContext;
    readonly upsertConciliacaoTarifa: typeof _mod.upsertConciliacaoTarifa;
    readonly fecharConciliacaoRecursoVsRelatorio: typeof _mod.fecharConciliacaoRecursoVsRelatorio;
    readonly reenviarFechamentoConciliacaoParaContabilidade: typeof _mod.reenviarFechamentoConciliacaoParaContabilidade;
    readonly reabrirConciliacaoRecursoVsRelatorio: typeof _mod.reabrirConciliacaoRecursoVsRelatorio;
    readonly deleteOrgaoDePara: typeof _mod.deleteOrgaoDePara;
    readonly exportConcilicacaoTemporarioXlsx: typeof _mod.exportConcilicacaoTemporarioXlsx;
    readonly exportConcilicacaoOcorrenciasXlsx: typeof _mod.exportConcilicacaoOcorrenciasXlsx;
    readonly listarConcilicacaoOcorrencias: typeof _mod.listarConcilicacaoOcorrencias;
    readonly exportConcilicacaoRecursoVsRelatorioXlsx: typeof _mod.exportConcilicacaoRecursoVsRelatorioXlsx;
    readonly exportRelatoriosValoresListaXlsx: typeof _mod.exportRelatoriosValoresListaXlsx;
    readonly exportConcilicacaoRecursoVsRelatorioPdf: typeof _mod.exportConcilicacaoRecursoVsRelatorioPdf;
    readonly getConciliacaoPorDataPreview: typeof _mod.getConciliacaoPorDataPreview;
    readonly exportConcilicacaoPorDataXlsx: typeof _mod.exportConcilicacaoPorDataXlsx;
    readonly exportConcilicacaoPorDataPdf: typeof _mod.exportConcilicacaoPorDataPdf;
    readonly requestConciliacaoPorDataValidation: typeof _mod.requestConciliacaoPorDataValidation;
    readonly decideConciliacaoPorDataValidation: typeof _mod.decideConciliacaoPorDataValidation;
    readonly getConciliacaoPorDataValidationPortalHtml: typeof _mod.getConciliacaoPorDataValidationPortalHtml;
    readonly getConsignadoAutomationConfig: typeof _mod.getConsignadoAutomationConfig;
    readonly getConsignadoAccessEmails: typeof _mod.getConsignadoAccessEmails;
    readonly setConsignadoAccessEmails: typeof _mod.setConsignadoAccessEmails;
    readonly getModalidades: typeof _mod.getModalidades;
    readonly saveModalidades: typeof _mod.saveModalidades;
    readonly getOrgaoColumnsConfig: typeof _mod.getOrgaoColumnsConfig;
    readonly saveOrgaoColumnsConfig: typeof _mod.saveOrgaoColumnsConfig;
    readonly getOrgaoDePara: typeof _mod.getOrgaoDePara;
    readonly upsertOrgaoDePara: typeof _mod.upsertOrgaoDePara;
    readonly getExtratosConsolidacaoRecurso: typeof _mod.getExtratosConsolidacaoRecurso;
    readonly upsertExtratosConsolidacaoRecurso: typeof _mod.upsertExtratosConsolidacaoRecurso;
    readonly deleteExtratosConsolidacaoRecurso: typeof _mod.deleteExtratosConsolidacaoRecurso;
    readonly getExtratosHistorico1Values: typeof _mod.getExtratosHistorico1Values;
    readonly getRecursoTableNames: typeof _mod.getRecursoTableNames;
    readonly getRelatorioConsolidacaoRecurso: typeof _mod.getRelatorioConsolidacaoRecurso;
    readonly upsertRelatorioConsolidacaoRecurso: typeof _mod.upsertRelatorioConsolidacaoRecurso;
    readonly deleteRelatorioConsolidacaoRecurso: typeof _mod.deleteRelatorioConsolidacaoRecurso;
    readonly importExtratosTemporarioFromBuffer: typeof _mod.importExtratosTemporarioFromBuffer;
    readonly importRelatoriosTemporarioFromBuffer: typeof _mod.importRelatoriosTemporarioFromBuffer;
    readonly listarFiltrosTemporario: typeof _mod.listarFiltrosTemporario;
    readonly listarMesesConcilicacaoDisponiveis: typeof _mod.listarMesesConcilicacaoDisponiveis;
    readonly listarPendenciasFluxoConcilicacao: typeof _mod.listarPendenciasFluxoConcilicacao;
    readonly atualizarPendenciaFluxoConcilicacao: typeof _mod.atualizarPendenciaFluxoConcilicacao;
    readonly listarAuditoriaSistemica: typeof _mod.listarAuditoriaSistemica;
    readonly saveConsignadoAutomationConfig: typeof _mod.saveConsignadoAutomationConfig;
    readonly searchGraphUsers: typeof _mod.searchGraphUsers;
    readonly importByLearningProfileFromFolderUrl: typeof _mod.importByLearningProfileFromFolderUrl;
    readonly importByLearningProfileFromShareUrl: typeof _mod.importByLearningProfileFromShareUrl;
    readonly runImportConsignado: typeof _mod.runImportConsignado;
    readonly sendDailyOccurrencesPanoramaEmail: typeof _mod.sendDailyOccurrencesPanoramaEmail;
    readonly listHomeConciliacaoStatuses: typeof _mod.listHomeConciliacaoStatuses;
    readonly importByLearningProfileFromFolderUrlResolved: typeof _mod.importByLearningProfileFromFolderUrl;
    readonly importByLearningProfileFromShareUrlResolved: typeof _mod.importByLearningProfileFromShareUrl;
    readonly runImportConsignadoResolved: typeof _mod.runImportConsignado;
    readonly getTeamsDelegatedLoginStatus: typeof _mod.getTeamsDelegatedLoginStatus;
    readonly startTeamsDelegatedDeviceCodeLogin: typeof _mod.startTeamsDelegatedDeviceCodeLogin;
    readonly finishTeamsDelegatedDeviceCodeLogin: typeof _mod.finishTeamsDelegatedDeviceCodeLogin;
    readonly disconnectTeamsDelegatedLogin: typeof _mod.disconnectTeamsDelegatedLogin;
    readonly debugEvent: (opts: unknown) => Promise<unknown>;
    readonly debugEnsureExtratosRelatoriosTables: () => Promise<{
        ok: boolean;
        dbFilePath: string;
        tablesAfter: Array<{
            name: string;
            columnsCount: number;
            rowCount?: number | null;
        }>;
        learningProfiles: Array<{
            id: string;
            kind: string;
            targetTable: string;
        }>;
        allTablesContainingExtratoOrRelatorio: Array<{
            name: string;
            rowCount: number | null;
            kind: string;
        }>;
        walCheckpointResult: unknown;
        lastExtratosRows: Array<Record<string, unknown>>;
        extratosColumns: Array<string>;
        adfegoEletraFound: Array<Record<string, unknown>>;
        extratosRowIdInfo: Record<string, unknown>;
    }>;
    readonly listImportJobsRecent: typeof _mod.listImportJobsRecent;
    readonly getImportJob: typeof _mod.getImportJob;
    readonly cancelImportJob: typeof _mod.cancelImportJob;
    readonly attachImportJobSse: typeof _mod.attachImportJobSse;
    readonly submitImportJobAsync: typeof _mod.submitImportJobAsync;
    readonly runAutomationDriveHealthCheck: typeof _mod.runAutomationDriveHealthCheck;
    readonly listAutomationSchedules: typeof _mod.listAutomationSchedules;
    readonly getAutomationSchedule: typeof _mod.getAutomationSchedule;
    readonly toggleAutomationSchedule: typeof _mod.toggleAutomationSchedule;
    readonly runAutomationScheduleNow: typeof _mod.runAutomationScheduleNow;
    readonly getAutomationGlobalConfig: typeof _mod.getAutomationConfig;
    readonly saveAutomationGlobalConfigPartial: typeof _mod.saveAutomationConfigPartial;
    readonly runAutomationHealthGeneral: typeof _mod.runAutomationHealthGeneral;
    readonly listAutomationImportFailures: typeof _mod.listAutomationImportFailures;
    readonly cleanupOldJobsTtl: typeof _mod.cleanupOldJobsTtl;
    readonly isTeamsMeetingUrl: (value: string) => boolean;
    isRecursoTarget(t: RecursoTarget | string): boolean;
}
export type { RecursoTarget };
